### ISSUE TITLE
注册队列问题

### ISSUE THREAD

**Issue by zunpan** [hyperchain/javasdk#104]
```
public static void main(String[] args) throws RequestException, IOException {
        HttpProvider httpProvider = new DefaultHttpProvider.Builder()
                .setUrl(nodeAddr)
                // .https(tlsca, tls_peer_cert, tls_peer_priv)
                .build();

        ProviderManager providerManager = ProviderManager.createManager(httpProvider);

        AccountService accountService = ServiceManager.getAccountService(providerManager);
        Account account = accountService.fromAccountJson(AccountUtil.getAccountFromJson());

        MQService mqService = ServiceManager.getMQService(providerManager);
        Request<MQResponse> request = mqService.informNormal(1);
        request.send();

        ArrayList<String> array = new ArrayList<String>();
        array.add("SignedMQBlock");
        array.add("MQLog");
        array.add("MQException");
        String qname = "node1queue";
        MQParam mqParam = new MQParam.Builder().  //队列订阅相关的参数
                msgTypes(array).     //表示要订阅的消息类型
                blockVerbose(false).
                queueName(qname).    //表示队列名称// MQlog事件订阅需要的参数
                logAddress(contractAddress).   //表示log事件需要匹配的合约地址
                logTopics(new String[]{"topicA"}). //表示log事件需要匹配的topic集合
                build();
        Request<MQResponse> mqResponseRequest = mqService.registerQueue(mqParam,1);
        MQResponse response = mqResponseRequest.send();

        // MQResponse response = mqService.registerQueue(account.getAddress(), qname, array, false, 1).send();
        List<String> queueNames = response.getQueueNames();
        for (int i = 0; i < queueNames.size(); i++) {
            System.out.println(queueNames.get(i));
        }
    }
```
注册队列时发生如下异常
`Exception in thread "main" cn.hyperchain.sdk.exception.RequestException: Invalid params: []interface {}: types.RegisterMeta.RoutingKeys: []string: From: Topics: [][]common.Hash: []common.Hash: unmarshalerDecoder: common: unmarshalJSON failed: hash must be exactly 32 bytes, error found in #10 byte of ...|[["topicA"]],"from":|..., bigger context ...|ignature":"","isVerbose":false,"topics":[["topicA"]],"from":"","routingKeys":["SignedMQBlock","MQLog|...
	at cn.hyperchain.sdk.request.Request.send(Request.java:102)
	at cn.hyperchain.sdk.request.MQRequest.send(MQRequest.java:18)
	at Mq.main(Mq.java:52)
`

使用另一种注册方式
```
public static void main(String[] args) throws RequestException, IOException {
        HttpProvider httpProvider = new DefaultHttpProvider.Builder()
                .setUrl(nodeAddr)
                // .https(tlsca, tls_peer_cert, tls_peer_priv)
                .build();

        ProviderManager providerManager = ProviderManager.createManager(httpProvider);

        AccountService accountService = ServiceManager.getAccountService(providerManager);
        Account account = accountService.fromAccountJson(AccountUtil.getAccountFromJson());

        MQService mqService = ServiceManager.getMQService(providerManager);
        Request<MQResponse> request = mqService.informNormal(1);
        request.send();

        ArrayList<String> array = new ArrayList<String>();
        array.add("SignedMQBlock");
        array.add("MQLog");
        array.add("MQException");
        String qname = "node1queue";
        // MQParam mqParam = new MQParam.Builder().  //队列订阅相关的参数
        //         msgTypes(array).     //表示要订阅的消息类型
        //         blockVerbose(false).
        //         queueName(qname).    //表示队列名称// MQlog事件订阅需要的参数
        //         logAddress(contractAddress).   //表示log事件需要匹配的合约地址
        //         logTopics(new String[]{"topicA"}). //表示log事件需要匹配的topic集合
        //         build();
        // Request<MQResponse> mqResponseRequest = mqService.registerQueue(mqParam,1);
        // MQResponse response = mqResponseRequest.send();

        MQResponse response = mqService.registerQueue(account.getAddress(), qname, array, false, 1).send();
        List<String> queueNames = response.getQueueNames();
        for (int i = 0; i < queueNames.size(); i++) {
            System.out.println(queueNames.get(i));
        }
    }
```
错误如下
`Exception in thread "main" cn.hyperchain.sdk.exception.RequestException: register queue with singed option but ERCert is closed
	at cn.hyperchain.sdk.request.Request.send(Request.java:102)
	at cn.hyperchain.sdk.request.MQRequest.send(MQRequest.java:18)
	at Mq.main(Mq.java:51)`

请问是少了什么参数吗

**Comment by zunpan** [comment]
litesdk版本如下
```
<dependency>
    <groupId>cn.hyperchain</groupId>
    <artifactId>litesdk</artifactId>
    <version>1.0.7</version>
</dependency>
```

**Comment by zunpan** [comment]
> ```
> public static void main(String[] args) throws RequestException, IOException {
>         HttpProvider httpProvider = new DefaultHttpProvider.Builder()
>                 .setUrl(nodeAddr)
>                 // .https(tlsca, tls_peer_cert, tls_peer_priv)
>                 .build();
> 
>         ProviderManager providerManager = ProviderManager.createManager(httpProvider);
> 
>         AccountService accountService = ServiceManager.getAccountService(providerManager);
>         Account account = accountService.fromAccountJson(AccountUtil.getAccountFromJson());
> 
>         MQService mqService = ServiceManager.getMQService(providerManager);
>         Request<MQResponse> request = mqService.informNormal(1);
>         request.send();
> 
>         ArrayList<String> array = new ArrayList<String>();
>         array.add("SignedMQBlock");
>         array.add("MQLog");
>         array.add("MQException");
>         String qname = "node1queue";
>         MQParam mqParam = new MQParam.Builder().  //队列订阅相关的参数
>                 msgTypes(array).     //表示要订阅的消息类型
>                 blockVerbose(false).
>                 queueName(qname).    //表示队列名称// MQlog事件订阅需要的参数
>                 logAddress(contractAddress).   //表示log事件需要匹配的合约地址
>                 logTopics(new String[]{"topicA"}). //表示log事件需要匹配的topic集合
>                 build();
>         Request<MQResponse> mqResponseRequest = mqService.registerQueue(mqParam,1);
>         MQResponse response = mqResponseRequest.send();
> 
>         // MQResponse response = mqService.registerQueue(account.getAddress(), qname, array, false, 1).send();
>         List<String> queueNames = response.getQueueNames();
>         for (int i = 0; i < queueNames.size(); i++) {
>             System.out.println(queueNames.get(i));
>         }
>     }
> ```
> 
> 注册队列时发生如下异常
> `Exception in thread "main" cn.hyperchain.sdk.exception.RequestException: Invalid params: []interface {}: types.RegisterMeta.RoutingKeys: []string: From: Topics: [][]common.Hash: []common.Hash: unmarshalerDecoder: common: unmarshalJSON failed: hash must be exactly 32 bytes, error found in #10 byte of ...|[["topicA"]],"from":|..., bigger context ...|ignature":"","isVerbose":false,"topics":[["topicA"]],"from":"","routingKeys":["SignedMQBlock","MQLog|... at cn.hyperchain.sdk.request.Request.send(Request.java:102) at cn.hyperchain.sdk.request.MQRequest.send(MQRequest.java:18) at Mq.main(Mq.java:52) `
> 
> 使用另一种注册方式
> 
> ```
> public static void main(String[] args) throws RequestException, IOException {
>         HttpProvider httpProvider = new DefaultHttpProvider.Builder()
>                 .setUrl(nodeAddr)
>                 // .https(tlsca, tls_peer_cert, tls_peer_priv)
>                 .build();
> 
>         ProviderManager providerManager = ProviderManager.createManager(httpProvider);
> 
>         AccountService accountService = ServiceManager.getAccountService(providerManager);
>         Account account = accountService.fromAccountJson(AccountUtil.getAccountFromJson());
> 
>         MQService mqService = ServiceManager.getMQService(providerManager);
>         Request<MQResponse> request = mqService.informNormal(1);
>         request.send();
> 
>         ArrayList<String> array = new ArrayList<String>();
>         array.add("SignedMQBlock");
>         array.add("MQLog");
>         array.add("MQException");
>         String qname = "node1queue";
>         // MQParam mqParam = new MQParam.Builder().  //队列订阅相关的参数
>         //         msgTypes(array).     //表示要订阅的消息类型
>         //         blockVerbose(false).
>         //         queueName(qname).    //表示队列名称// MQlog事件订阅需要的参数
>         //         logAddress(contractAddress).   //表示log事件需要匹配的合约地址
>         //         logTopics(new String[]{"topicA"}). //表示log事件需要匹配的topic集合
>         //         build();
>         // Request<MQResponse> mqResponseRequest = mqService.registerQueue(mqParam,1);
>         // MQResponse response = mqResponseRequest.send();
> 
>         MQResponse response = mqService.registerQueue(account.getAddress(), qname, array, false, 1).send();
>         List<String> queueNames = response.getQueueNames();
>         for (int i = 0; i < queueNames.size(); i++) {
>             System.out.println(queueNames.get(i));
>         }
>     }
> ```
> 
> 错误如下
> `Exception in thread "main" cn.hyperchain.sdk.exception.RequestException: register queue with singed option but ERCert is closed at cn.hyperchain.sdk.request.Request.send(Request.java:102) at cn.hyperchain.sdk.request.MQRequest.send(MQRequest.java:18) at Mq.main(Mq.java:51)`
> 
> 请问是少了什么参数吗

第二种方式把array.add("SignedMQBlock");去掉可以注册成功
